steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 
      'build', 
      '--cache-from',
      'eu.gcr.io/$PROJECT_ID/autosuggest-app:latest',
      '-f' , './autosuggest-app/Dockerfile', 
      '--tag=eu.gcr.io/$PROJECT_ID/autosuggest-app:$TAG_NAME', 
      './autosuggest-app' 
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'tag', 'eu.gcr.io/$PROJECT_ID/autosuggest-app:$TAG_NAME', 'eu.gcr.io/$PROJECT_ID/autosuggest-app:latest' ]

images:
  - 'eu.gcr.io/$PROJECT_ID/autosuggest-app:$TAG_NAME'
  - 'eu.gcr.io/$PROJECT_ID/autosuggest-app:latest'
