steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 
      'build', 
      '--cache-from',
      'eu.gcr.io/$PROJECT_ID/autosuggest-app:latest',
      '-f' , './Dockerfile', 
      '--tag=eu.gcr.io/$PROJECT_ID/autosuggest-app:$TAG_NAME', 
      '.' 
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'tag', 'eu.gcr.io/$PROJECT_ID/autosuggest-app:$TAG_NAME', 'eu.gcr.io/$PROJECT_ID/autosuggest-app:latest' ]

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'patch'
      - 'deployment'
      - 'autosuggest-app-deployment'
      - '-n'
      - 'autosuggest-dev'
      - '-o'
      - 'yaml'
      - '-p'
      - |
        spec:
          template:
            spec:
              containers:
                - name: autosuggest-app
                  image: eu.gcr.io/$PROJECT_ID/autosuggest-app:$TAG_NAME
#      '{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"autosuggest-app\",\"image\":\"eu.gcr.io/$PROJECT_ID/autosuggest-app:$TAG_NAME\"}]}}}}'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-d'
    - 'CLOUDSDK_CONTAINER_CLUSTER=autosuggest-cluster-eu'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'patch'
      - 'deployment'
      - 'autosuggest-app-deployment'
      - '-n'
      - 'autosuggest-dev'
      - '-o'
      - 'yaml'
      - '-p'
      - |
        spec:
          template:
            spec:
              containers:
                - name: autosuggest-app
                  image: eu.gcr.io/$PROJECT_ID/autosuggest-app:$TAG_NAME
#      '{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"autosuggest-app\",\"image\":\"eu.gcr.io/$PROJECT_ID/autosuggest-app:$TAG_NAME\"}]}}}}'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=autosuggest-cluster-us'

images:
  - 'eu.gcr.io/$PROJECT_ID/autosuggest-app:$TAG_NAME'
  - 'eu.gcr.io/$PROJECT_ID/autosuggest-app:latest'
